module.exports = {
  WRONG_USER: "WRONG_USER",
  WRONG_PASS: "WRONG_PASS",
  WRONG_FORM: "WRONG_FORM",
  GOOD_USER: "GOOD_USER",

  UNVERIFIED: "UNVERIFIED",

  SUSPENDED: "SUSPENDED",

  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  STORE_GET: "STORE_GET",
  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  REG_SUCCESS: "REG_SUCCESS",
  CREATE_NEW_STORE: "CREATE_NEW_STORE"
};
